name = "SentryIntegration"
uuid = "0c0dc41a-7892-49ef-a372-46007ef8f0a8"
authors = ["Daniel Cocks <daniel.cocks@gmail.com>"]
version = "0.6.2"

[deps]
CodecZlib = "944b1d66-785c-5afd-91f1-9de20f533193"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
HTTP = "cd3eb016-35fb-5094-929b-558a96fad6f3"
JSON3 = "0f8b85d8-7281-11e9-16c2-39a750bddbf1"
Logging = "56ddb016-857b-54e1-b83d-db4d58db5568"
Pkg = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
UUIDs = "cf7118a7-6976-5b1a-9a39-7adc72f591a4"
